"""rename address

Revision ID: 973a513f5d39
Revises: af99a08d2f5e
Create Date: 2025-03-28 14:19:15.068755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973a513f5d39'
down_revision = 'af99a08d2f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name='address')
    # ### end Alembic commands ###
